source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CHVIpify_Example', :exclusive => true do
  pod "CHVIpify", :path => "../"
end

target 'CHVIpify_Tests', :exclusive => true do
  pod "CHVIpify", :path => "../"

  
end
